### ISSUE TITLE
Quotes on the command line are interpreted by bash, not by jo

### ISSUE THREAD

**Issue by cdbennett** [OrhanKupusoglu/jo-jq#2]
The section saying "jo is clever with types so that you can ignore double quotes when appropriate" is incorrect. The quotes, both double and single quotes, are interpreted by the shell and stripped from the command line arguments before the `jo` program receives them.

So it's not `jo` that handles quotes, or deals with arguments having embedded spaces, but the shell itself does this. It's helpful to clarify and understand quotes and command line argument passing because it is a common source of misunderstanding and latent bugs.

**Comment by OrhanKupusoglu** [comment]
Although I would prefer that you review the PR, I elected to approve the PR.
If you have any remarks, please do not hesitate.

**Comment by cdbennett** [comment]
Looks good, thanks for the clarification!

**Comment by OrhanKupusoglu** [comment]
Thanks for your interest & contribution.

Orhan
